### PR TITLE
Extended API typings

### LINKED ISSUE #5: Inconsistency in typings
The [`getDeviceToken` method of this library](https://github.com/TuyaAPI/openapi/blob/master/src/api.ts#L152) has a return type of `Promise<string>`

While after [link library fetches it](https://github.com/TuyaAPI/link/blob/master/index.js#L85) it is [treated as an object](https://github.com/TuyaAPI/link/blob/master/index.js#L89).

Logically it can't be both 😛

### PR DESCRIPTION
**Pull request by milo526**
Changed the default `object` typings to more specific typings.
Fixed some API endpoints that were wrongly typed as `Promise<string>`,
which should also have been of the `object` type.

Fixes #5 

This is preparation work for https://github.com/TuyaAPI/link/issues/11

### CODE REVIEW

**Comment by milo526** [comment]
I have no idea how I should open the documentation locally 🙈 so that part was not checked - it is however automatically generated without further alterations from me.

**Comment by codetheweb** [comment]
Thanks, LGTM.

The docs seem to be somewhat broken because nothing seems to be linked from `index.html`. I'll try to fix that after merging this.

**Comment by codetheweb** [comment]
[Docs are now fixed](https://github.com/TuyaAPI/openapi/blob/master/docs/classes/api.openapi.md).

**Comment by milo526** [comment]
Thank you for being such pro-active and quick about all of this!

it's nice to see this get merged and quickly so swiftly.

**Comment by codetheweb** [comment]
Travis seems to currently be broken for some reason, but this should now be published in v1.2.2.

**Pull request merged**
